// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Golang
func (r *Binding) AsGolang() *Golang { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L41)
	q := r.query.Select("asGolang")

	return &Golang{
		query: q,
	}
}

// Create or update a binding of type Golang in the environment
func (r *Env) WithGolangInput(name string, value *Golang, description string) *Env { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L41)
	assertNotNil("value", value)
	q := r.query.Select("withGolangInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Golang output to be assigned in the environment
func (r *Env) WithGolangOutput(name string, description string) *Env { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L41)
	q := r.query.Select("withGolangOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Golang dagger module
type Golang struct { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L41)
	query *querybuilder.Selection

	bench      *string
	goBin      *string
	id         *ID
	lint       *string
	modVersion *string
	vulncheck  *string
}
type WithGolangFunc func(r *Golang) *Golang

// With calls the provided function with current Golang.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *Golang) With(f WithGolangFunc) *Golang {
	return f(r)
}

func (r *Golang) WithGraphQLQuery(q *querybuilder.Selection) *Golang {
	return &Golang{
		query: q,
	}
}

// GolangBenchOpts contains options for Golang.Bench
type GolangBenchOpts struct {
	//
	// print memory allocation statistics for benchmarks
	//
	//
	// Default: true
	Memory bool // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L409)
	//
	// the time.Duration each benchmark should run for
	//
	//
	// Default: "5s"
	Time string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L413)
}

// Execute benchmarks defined within the target project, excludes all other tests
func (r *Golang) Bench(ctx context.Context, opts ...GolangBenchOpts) (string, error) { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L404)
	if r.bench != nil {
		return *r.bench, nil
	}
	q := r.query.Select("bench")
	for i := len(opts) - 1; i >= 0; i-- {
		// `memory` optional argument
		if !querybuilder.IsZeroValue(opts[i].Memory) {
			q = q.Arg("memory", opts[i].Memory)
		}
		// `time` optional argument
		if !querybuilder.IsZeroValue(opts[i].Time) {
			q = q.Arg("time", opts[i].Time)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// GolangBuildOpts contains options for Golang.Build
type GolangBuildOpts struct {
	//
	// the path to the main.go file of the project
	//
	Main string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L236)
	//
	// the name of the built binary
	//
	Out string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L239)
	//
	// the target operating system
	//
	Os string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L242)
	//
	// the target architecture
	//
	Arch string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L245)
	//
	// flags to configure the linking during a build, by default sets flags for
	// generating a release binary
	//
	//
	// Default: ["-s","-w"]
	Ldflags []string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L250)
}

// Build a static binary from a Go project using the provided configuration.
// A directory is returned containing the built binary.
func (r *Golang) Build(opts ...GolangBuildOpts) *Directory { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L233)
	q := r.query.Select("build")
	for i := len(opts) - 1; i >= 0; i-- {
		// `main` optional argument
		if !querybuilder.IsZeroValue(opts[i].Main) {
			q = q.Arg("main", opts[i].Main)
		}
		// `out` optional argument
		if !querybuilder.IsZeroValue(opts[i].Out) {
			q = q.Arg("out", opts[i].Out)
		}
		// `os` optional argument
		if !querybuilder.IsZeroValue(opts[i].Os) {
			q = q.Arg("os", opts[i].Os)
		}
		// `arch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Arch) {
			q = q.Arg("arch", opts[i].Arch)
		}
		// `ldflags` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ldflags) {
			q = q.Arg("ldflags", opts[i].Ldflags)
		}
	}

	return &Directory{
		query: q,
	}
}

// GolangCiOpts contains options for Golang.Ci
type GolangCiOpts struct {
	//
	// Path to main.go
	//
	Main string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L22)
	//
	// Binary output name
	//
	Out string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L25)
	//
	// Target OS
	//
	Os string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L28)
	//
	// Target arch
	//
	Arch string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L31)
	//
	// ldflags
	//
	Ldflags []string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L34)
}

// Ci runs lint, test, and build as a single CI entrypoint.
func (r *Golang) Ci(opts ...GolangCiOpts) *Directory { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L18)
	q := r.query.Select("ci")
	for i := len(opts) - 1; i >= 0; i-- {
		// `main` optional argument
		if !querybuilder.IsZeroValue(opts[i].Main) {
			q = q.Arg("main", opts[i].Main)
		}
		// `out` optional argument
		if !querybuilder.IsZeroValue(opts[i].Out) {
			q = q.Arg("out", opts[i].Out)
		}
		// `os` optional argument
		if !querybuilder.IsZeroValue(opts[i].Os) {
			q = q.Arg("os", opts[i].Os)
		}
		// `arch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Arch) {
			q = q.Arg("arch", opts[i].Arch)
		}
		// `ldflags` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ldflags) {
			q = q.Arg("ldflags", opts[i].Ldflags)
		}
	}

	return &Directory{
		query: q,
	}
}

// Base is the image used by all golang dagger functions, defaults to the bookworm base image
func (r *Golang) Container() *Container { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L43)
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// GolangDebugTestOpts contains options for Golang.DebugTest
type GolangDebugTestOpts struct {
	//
	// run select tests only, defined using a regex
	//
	Run string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L354)
}

// Execute tests defined within the target project, ignores benchmarks by default
// Debug test with dlv
func (r *Golang) DebugTest(opts ...GolangDebugTestOpts) *Service { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L350)
	q := r.query.Select("debugTest")
	for i := len(opts) - 1; i >= 0; i-- {
		// `run` optional argument
		if !querybuilder.IsZeroValue(opts[i].Run) {
			q = q.Arg("run", opts[i].Run)
		}
	}

	return &Service{
		query: q,
	}
}

// Format the source code within a target project using gofumpt. Formatted code must be
// copied back onto the host.`
func (r *Golang) Format() *Directory { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L498)
	q := r.query.Select("format")

	return &Directory{
		query: q,
	}
}

// GolangGenerateCiOpts contains options for Golang.GenerateCi
type GolangGenerateCiOpts struct {
	//
	// Branches that trigger the pipeline
	//
	//
	// Default: ["main"]
	Branches []string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L74)
	//
	// Dagger CLI version to use in CI (empty = engine default)
	//
	DaggerVersion string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L78)
	//
	// Branch commits land here when running on a tag.
	//
	//
	// Default: "main"
	DefaultBranch string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L83)
	//
	// Configurable dagger module reference.
	// Defaults to this module's current version (auto-detected).
	//
	ModuleRef string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L88)
	//
	// GitHub: secret name for registry username (empty = github.actor).
	//
	RegistryUsernameKey string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L92)
	//
	// GitHub: secret name for registry password (empty = GITHUB_TOKEN).
	//
	RegistryPasswordKey string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L96)
	//
	// Jenkins: credential id for registry username/password.
	//
	RegistryCredential string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L100)
	//
	// Jenkins: credential id for git token.
	//
	GitTokenCredential string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L104)
	//
	// GitLab: CI/CD variable name for registry username.
	//
	RegistryUsernameVar string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L108)
	//
	// GitLab: CI/CD variable name for registry password.
	//
	RegistryPasswordVar string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L112)
	//
	// GitLab: CI/CD variable name for git token.
	//
	GitTokenVar string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L116)
	//
	// Jenkins: dagger kubernetes token credential ID.
	// When set, the Jenkinsfile uses the daggerKubernetes shared library step.
	//
	DaggerKubernetesToken string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L121)
	//
	// Jenkins: dagger kubernetes server URL.
	//
	DaggerKubernetesURL string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L125)
	//
	// Force overwrite DAGGER.md even if it already exists in source.
	//
	ForceDaggerMd bool // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L129)
}

// GenerateCi generates CI pipeline files for the given CI system.
func (r *Golang) GenerateCi(ci string, opts ...GolangGenerateCiOpts) *Directory { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/pipeline.go#L64)
	q := r.query.Select("generateCi")
	for i := len(opts) - 1; i >= 0; i-- {
		// `branches` optional argument
		if !querybuilder.IsZeroValue(opts[i].Branches) {
			q = q.Arg("branches", opts[i].Branches)
		}
		// `daggerVersion` optional argument
		if !querybuilder.IsZeroValue(opts[i].DaggerVersion) {
			q = q.Arg("daggerVersion", opts[i].DaggerVersion)
		}
		// `defaultBranch` optional argument
		if !querybuilder.IsZeroValue(opts[i].DefaultBranch) {
			q = q.Arg("defaultBranch", opts[i].DefaultBranch)
		}
		// `moduleRef` optional argument
		if !querybuilder.IsZeroValue(opts[i].ModuleRef) {
			q = q.Arg("moduleRef", opts[i].ModuleRef)
		}
		// `registryUsernameKey` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryUsernameKey) {
			q = q.Arg("registryUsernameKey", opts[i].RegistryUsernameKey)
		}
		// `registryPasswordKey` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryPasswordKey) {
			q = q.Arg("registryPasswordKey", opts[i].RegistryPasswordKey)
		}
		// `registryCredential` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryCredential) {
			q = q.Arg("registryCredential", opts[i].RegistryCredential)
		}
		// `gitTokenCredential` optional argument
		if !querybuilder.IsZeroValue(opts[i].GitTokenCredential) {
			q = q.Arg("gitTokenCredential", opts[i].GitTokenCredential)
		}
		// `registryUsernameVar` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryUsernameVar) {
			q = q.Arg("registryUsernameVar", opts[i].RegistryUsernameVar)
		}
		// `registryPasswordVar` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryPasswordVar) {
			q = q.Arg("registryPasswordVar", opts[i].RegistryPasswordVar)
		}
		// `gitTokenVar` optional argument
		if !querybuilder.IsZeroValue(opts[i].GitTokenVar) {
			q = q.Arg("gitTokenVar", opts[i].GitTokenVar)
		}
		// `daggerKubernetesToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].DaggerKubernetesToken) {
			q = q.Arg("daggerKubernetesToken", opts[i].DaggerKubernetesToken)
		}
		// `daggerKubernetesUrl` optional argument
		if !querybuilder.IsZeroValue(opts[i].DaggerKubernetesURL) {
			q = q.Arg("daggerKubernetesUrl", opts[i].DaggerKubernetesURL)
		}
		// `forceDaggerMd` optional argument
		if !querybuilder.IsZeroValue(opts[i].ForceDaggerMd) {
			q = q.Arg("forceDaggerMd", opts[i].ForceDaggerMd)
		}
	}
	q = q.Arg("ci", ci)

	return &Directory{
		query: q,
	}
}

// GoBin return the Go bin path
// It can be usefull to add bin on this because of cache volume
func (r *Golang) GoBin(ctx context.Context) (string, error) { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L159)
	if r.goBin != nil {
		return *r.goBin, nil
	}
	q := r.query.Select("goBin")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this Golang.
func (r *Golang) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Golang) XXX_GraphQLType() string {
	return "Golang"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Golang) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Golang) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Golang) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Golang) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Golang{query: selectNode(dag.query, id, "Golang")}
	return nil
}

// Lint the target project using golangci-lint
func (r *Golang) Lint(ctx context.Context) (string, error) { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L454)
	if r.lint != nil {
		return *r.lint, nil
	}
	q := r.query.Select("lint")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Echoes the version of go defined within a projects go.mod file.
// It expects the go.mod file to be located within the root of the project
func (r *Golang) ModVersion(ctx context.Context) (string, error) { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L153)
	if r.modVersion != nil {
		return *r.modVersion, nil
	}
	q := r.query.Select("modVersion")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// GolangTestOpts contains options for Golang.Test
type GolangTestOpts struct {
	//
	// if only short running tests should be executed
	//
	Short bool // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L287)
	//
	// if the tests should be executed out of order
	//
	Shuffle bool // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L290)
	//
	// run select tests only, defined using a regex
	//
	Run string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L293)
	//
	// skip select tests, defined using a regex
	//
	Skip string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L296)
	//
	// Run test with gotestsum
	//
	WithGotestsum bool // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L299)
	//
	// Path to test
	//
	Path string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L302)
}

// Execute tests defined within the target project, ignores benchmarks by default
func (r *Golang) Test(opts ...GolangTestOpts) *File { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L283)
	q := r.query.Select("test")
	for i := len(opts) - 1; i >= 0; i-- {
		// `short` optional argument
		if !querybuilder.IsZeroValue(opts[i].Short) {
			q = q.Arg("short", opts[i].Short)
		}
		// `shuffle` optional argument
		if !querybuilder.IsZeroValue(opts[i].Shuffle) {
			q = q.Arg("shuffle", opts[i].Shuffle)
		}
		// `run` optional argument
		if !querybuilder.IsZeroValue(opts[i].Run) {
			q = q.Arg("run", opts[i].Run)
		}
		// `skip` optional argument
		if !querybuilder.IsZeroValue(opts[i].Skip) {
			q = q.Arg("skip", opts[i].Skip)
		}
		// `withGotestsum` optional argument
		if !querybuilder.IsZeroValue(opts[i].WithGotestsum) {
			q = q.Arg("withGotestsum", opts[i].WithGotestsum)
		}
		// `path` optional argument
		if !querybuilder.IsZeroValue(opts[i].Path) {
			q = q.Arg("path", opts[i].Path)
		}
	}

	return &File{
		query: q,
	}
}

// Scans the target project for vulnerabilities using govulncheck
func (r *Golang) Vulncheck(ctx context.Context) (string, error) { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L429)
	if r.vulncheck != nil {
		return *r.vulncheck, nil
	}
	q := r.query.Select("vulncheck")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Enable private Go module support by dynamically constructing a .netrc auto-login
// configuration file. Each call will append a new auto-login configuration
func (r *Golang) WithPrivate(machine string, username *Secret, password *Secret, modules []string) *Golang { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L169)
	assertNotNil("username", username)
	assertNotNil("password", password)
	q := r.query.Select("withPrivate")
	q = q.Arg("machine", machine)
	q = q.Arg("username", username)
	q = q.Arg("password", password)
	q = q.Arg("modules", modules)

	return &Golang{
		query: q,
	}
}

// Enable private Go module support by loading an existing .netrc auto-login configuration
// file. Each call will append a new auto-login configuration
func (r *Golang) WithPrivateLoad(cfg *File, modules []string) *Golang { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L199)
	assertNotNil("cfg", cfg)
	q := r.query.Select("withPrivateLoad")
	q = q.Arg("cfg", cfg)
	q = q.Arg("modules", modules)

	return &Golang{
		query: q,
	}
}

// WithSource permit to update the current source on sdk container
func (r *Golang) WithSource(src *Directory) *Golang { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L515)
	assertNotNil("src", src)
	q := r.query.Select("withSource")
	q = q.Arg("src", src)

	return &Golang{
		query: q,
	}
}

// AsNode returns this Golang as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Golang) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// GolangOpts contains options for Query.Golang
type GolangOpts struct {
	//
	// A custom base image containing an installation of golang. If no image is provided,
	// one is resolved based on the Go version defined within the projects go.mod file. The
	// official Go image is pulled from DockerHub using either the bullseye (< 1.20) or
	// bookworm (> 1.20) variants.
	//
	Base *Container // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L67)
	//
	// The golang version to use when no go.mod
	//
	Version string // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L70)
}

// New initializes the golang dagger module
func (r *Query) Golang(src *Directory, opts ...GolangOpts) *Golang { // golang (https://github.com/disaster37/dagger-library-go/tree/e205189be6eba617e7bcc870db2e73a04171f38e/golang/main.go#L60)
	assertNotNil("src", src)
	q := r.query.Select("golang")
	for i := len(opts) - 1; i >= 0; i-- {
		// `base` optional argument
		if !querybuilder.IsZeroValue(opts[i].Base) {
			q = q.Arg("base", opts[i].Base)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}
	q = q.Arg("src", src)

	return &Golang{
		query: q,
	}
}
