// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Goreleaser
func (r *Binding) AsGoreleaser() *Goreleaser { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/main.go#L7)
	q := r.query.Select("asGoreleaser")

	return &Goreleaser{
		query: q,
	}
}

// Retrieve the binding value, as type GoreleaserTestResult
func (r *Binding) AsGoreleaserTestResult() *GoreleaserTestResult { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/test.go#L39)
	q := r.query.Select("asGoreleaserTestResult")

	return &GoreleaserTestResult{
		query: q,
	}
}

// Create or update a binding of type Goreleaser in the environment
func (r *Env) WithGoreleaserInput(name string, value *Goreleaser, description string) *Env { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/main.go#L7)
	assertNotNil("value", value)
	q := r.query.Select("withGoreleaserInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Goreleaser output to be assigned in the environment
func (r *Env) WithGoreleaserOutput(name string, description string) *Env { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/main.go#L7)
	q := r.query.Select("withGoreleaserOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type GoreleaserTestResult in the environment
func (r *Env) WithGoreleaserTestResultInput(name string, value *GoreleaserTestResult, description string) *Env { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/test.go#L39)
	assertNotNil("value", value)
	q := r.query.Select("withGoreleaserTestResultInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired GoreleaserTestResult output to be assigned in the environment
func (r *Env) WithGoreleaserTestResultOutput(name string, description string) *Env { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/test.go#L39)
	q := r.query.Select("withGoreleaserTestResultOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type Goreleaser struct { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/main.go#L7)
	query *querybuilder.Selection

	id   *ID
	lint *string
	run  *string
}

func (r *Goreleaser) WithGraphQLQuery(q *querybuilder.Selection) *Goreleaser {
	return &Goreleaser{
		query: q,
	}
}

// Base container to build and test Goreleaser
func (r *Goreleaser) Base() *Container { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/build.go#L35)
	q := r.query.Select("base")

	return &Container{
		query: q,
	}
}

// GoreleaserBuildOpts contains options for Goreleaser.Build
type GoreleaserBuildOpts struct {
	//
	// Target OS to build
	//
	//
	// Default: "linux"
	Os string // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/build.go#L18)
	//
	// Target architecture to build
	//
	Arch string // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/build.go#L21)
}

// Build Goreleaser
func (r *Goreleaser) Build(opts ...GoreleaserBuildOpts) *File { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/build.go#L15)
	q := r.query.Select("build")
	for i := len(opts) - 1; i >= 0; i-- {
		// `os` optional argument
		if !querybuilder.IsZeroValue(opts[i].Os) {
			q = q.Arg("os", opts[i].Os)
		}
		// `arch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Arch) {
			q = q.Arg("arch", opts[i].Arch)
		}
	}

	return &File{
		query: q,
	}
}

// Container to build Goreleaser
func (r *Goreleaser) BuildEnv() *Container { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/build.go#L59)
	q := r.query.Select("buildEnv")

	return &Container{
		query: q,
	}
}

// A unique identifier for this Goreleaser.
func (r *Goreleaser) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Goreleaser) XXX_GraphQLType() string {
	return "Goreleaser"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Goreleaser) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Goreleaser) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Goreleaser) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Goreleaser) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Goreleaser{query: selectNode(dag.query, id, "Goreleaser")}
	return nil
}

// GoreleaserLintOpts contains options for Goreleaser.Lint
type GoreleaserLintOpts struct {
	//
	// Version of golangci-lint to use
	//
	//
	// Default: "v1.58.1"
	GolangciLintVersion string // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/lint.go#L13)
}

// Lint Goreleaser
func (r *Goreleaser) Lint(ctx context.Context, opts ...GoreleaserLintOpts) (string, error) { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/lint.go#L9)
	if r.lint != nil {
		return *r.lint, nil
	}
	q := r.query.Select("lint")
	for i := len(opts) - 1; i >= 0; i-- {
		// `golangciLintVersion` optional argument
		if !querybuilder.IsZeroValue(opts[i].GolangciLintVersion) {
			q = q.Arg("golangciLintVersion", opts[i].GolangciLintVersion)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Run Goreleaser
func (r *Goreleaser) Run(ctx context.Context, context *Directory, args []string) (string, error) { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/run.go#L11)
	assertNotNil("context", context)
	if r.run != nil {
		return *r.run, nil
	}
	q := r.query.Select("run")
	q = q.Arg("context", context)
	q = q.Arg("args", args)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Test Goreleaser
func (r *Goreleaser) Test() *GoreleaserTestResult { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/test.go#L18)
	q := r.query.Select("test")

	return &GoreleaserTestResult{
		query: q,
	}
}

// Container to test Goreleaser
func (r *Goreleaser) TestEnv() *Container { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/test.go#L55)
	q := r.query.Select("testEnv")

	return &Container{
		query: q,
	}
}

// AsNode returns this Goreleaser as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Goreleaser) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// Custom type for test results
type GoreleaserTestResult struct { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/test.go#L39)
	query *querybuilder.Selection

	id     *ID
	output *string
}

func (r *GoreleaserTestResult) WithGraphQLQuery(q *querybuilder.Selection) *GoreleaserTestResult {
	return &GoreleaserTestResult{
		query: q,
	}
}

// Container with the test executed
func (r *GoreleaserTestResult) Container() *Container { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/test.go#L41)
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// Coverage report from the test. Save with '-o ./coverage.txt'
func (r *GoreleaserTestResult) CoverageReport() *File { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/test.go#L45)
	q := r.query.Select("coverageReport")

	return &File{
		query: q,
	}
}

// A unique identifier for this GoreleaserTestResult.
func (r *GoreleaserTestResult) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *GoreleaserTestResult) XXX_GraphQLType() string {
	return "GoreleaserTestResult"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *GoreleaserTestResult) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *GoreleaserTestResult) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *GoreleaserTestResult) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *GoreleaserTestResult) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = GoreleaserTestResult{query: selectNode(dag.query, id, "GoreleaserTestResult")}
	return nil
}

// Stdout from the test command
func (r *GoreleaserTestResult) Output(ctx context.Context) (string, error) { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/test.go#L50)
	if r.output != nil {
		return *r.output, nil
	}
	q := r.query.Select("output")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this GoreleaserTestResult as a Node.
// This is a local type conversion — no GraphQL call.
func (r *GoreleaserTestResult) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// GoreleaserOpts contains options for Query.Goreleaser
type GoreleaserOpts struct {
	//
	// The Goreleaser source code to use
	//
	Source *Directory // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/main.go#L16)
}

// A module for Goreleaser Dagger functions
func (r *Query) Goreleaser(opts ...GoreleaserOpts) *Goreleaser { // goreleaser (https://github.com/goreleaser/goreleaser/tree/063c5d5b5c66fbdeaf5c50aeca444f5b581ec849/dagger/main.go#L12)
	q := r.query.Select("goreleaser")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
	}

	return &Goreleaser{
		query: q,
	}
}
